Add test for file not found
rdf-ext/rdf-utils-fs pull request #9
Opened 2022-04-21 17:59 UTC by cristianvasquez

I thought this component was not handling that part but it appears to work. :)
https://github.com/rdf-ext/rdf-utils-fs/issues/8

2022-04-26 07:41 UTC, bergos commented
@cristianvasquez can you replace the `asyncThrows` with [assert.rejects](https://nodejs.org/api/assert.html#assertrejectsasyncfn-error-message)? I guess `getStream` could be replaced with `stream.resume()`. Then there would be no need for new dependencies.

2022-04-26 08:26 UTC, cristianvasquez commented
```
const stream = fromFile('not_found.ttl')
stream.resume()
```
However, that will not throw exceptions. Is that expected?

2022-04-26 08:27 UTC, cristianvasquez commented
I've done the changes in my branch

2022-05-07 21:53 UTC, bergos commented
`.resume()` works, but the error is thrown after the async function is finished. You can add this line to wait for the error:

```javascript
const { promisify } = require('util')
const { finished } = require('readable-stream')

// line after stream.resume()
await promisify(finished)(stream)
```

2022-05-07 21:55 UTC, bergos requested changes

2022-05-07 21:55 UTC, bergos commented on test/fromFile.test.js
> +        fromFile('test.jpg')
A sync error is thrown and `throws()` should be used. An `await` would be required if an async error is thrown.

2022-05-07 21:55 UTC, bergos commented on test/fromFile.test.js
> +        fromFile('test.jpg', {
Same here, a sync error is thrown.

2022-06-09 12:45 UTC, cristianvasquez commented
I did the changes as requested

thanks for the review, I learned some things.

2026-01-09 09:36 UTC, closed without merging